apiVersion: v1
    kind: ConfigMap
    metadata:
    name: erp-server-configmap
    namespace: erp
    data:
    BNR_BASE_URL: "http://bnr-server-service.bnr.svc.cluster.local"
    STORE_BASE_URL: "http://store-server-service.store.svc.cluster.local"
    OMS_BASE_URL: "http://oms-server-service.oms.svc.cluster.local"
    ERP_BASE_URL: "http://erp-server-service.erp.svc.cluster.local"
