apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: shop-client-service
spec:
  selector:
    app: shop-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
