apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: shop-server-service
spec:
  selector:
    app: shop-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
