apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: shop-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-server
  template:
    metadata:
      labels:
        app: shop-server
    spec:
      containers:
        - name: shop-server
          image: staticaldust/stam:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: demo-store-secret
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: demo-store-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-store-secret
                  key: JWT_SECRET
