apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnr-client-deployment
  namespace: bnr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bnr-client
  template:
    metadata:
      labels:
        app: bnr-client
    spec:
      containers:
        - name: bnr-client
        namespace: bnr
          # image: yakovperets/devops-shop-client:1
          ports:
            - containerPort: 3000
            
