apiVersion: v1
kind: Service
metadata:
  namespace: bnr
  name: bnr-server-service
spec:
  selector:
    app: bnr-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP