apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bnr
  name: bnr-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnr-server
  template:
    metadata:
      labels:
        app: bnr-server
    spec:
      containers:
        - name: bnr-server
          image: staticaldust/stam:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: bnr-mongodb-secret
                  namespace: bnr
                  key: PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: bnr-mongodb-secret
                  namespace: bnr
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bnr-mongodb-secret
                  namespace: bnr
                  key: JWT_SECRET
            - name: POSTGRESQL_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: bnr-postgresql-secret
                  namespace: bnr
                  key: POSTGRESQL_CONNECTION_STRING
            - name: APP_ENV
              valueFrom:
                configMapRef:
                  name: bnr-server-configmap
                  namespace: bnr
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapRef:
                  name: bnr-server-configmap
                  namespace: bnr
                  key: LOG_LEVEL
            - name: GMAIL_USERNAME
              valueFrom:
                configMapRef:
                  name: bnr-server-configmap
                  namespace: bnr
                  key: GMAIL_USERNAME
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                configMapRef:
                  name: bnr-server-configmap
                  namespace: bnr
                  key: GMAIL_APP_PASSWORD
