apiVersion: v1
kind: Service
metadata:
  namespace: bnr
  name: bnr-client-service
spec:
  selector:
    app: bnr-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
