apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: ingress-namespace
spec:
  rules:
    - host:
      http:
        paths:
          - path: /bnr
            pathType: Prefix
            backend:
              service:
                name: your-service-1
                port:
                  number: 80
          - path: /erp
            pathType: Prefix
            backend:
              service:
                name: your-service-2
                port:
                  number: 80
          - path: /oms
            pathType: Prefix
            backend:
              service:
                name: your-service-3
                port:
                  number: 80
          - path: /store
            pathType: Prefix
            backend:
              service:
                name: your-service-4
                port:
                  number: 80
