apiVersion: v1
kind: Service
metadata:
  namespace: store
  name: store-client-service
  namespace: store
spec:
  selector:
    app: store-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  
